## desicion tree

In [ ]:
a descision  tree is a suprevised ml algo that is used for classification and regreation .
it has 3 node 
1---> root node---> intrepeernal node ---> 3 leaf node 
1 root node ---> 1 feature  to split 
2 internal node ---> conditional (feature based question )
3 leaf node -----> final node (class/label/value)

-----> how it works 
1) select the best feature to split data 
2) split the data based on feature 
3) repeat the process recursively for each branch 
4) stop when all data belong  same class 
5) maxs dept is reached ----> no significants gain for further split  
## key conscept for spliting 
1) gini index ---> the gini index measures the purity or impurity of the data set .it tells how ofen a randomly chosine a element would 
                    be incorettly lable . if randomly lable accr to the distribution to the node 
                gini(b)=1-sum of prob()**2
    :-c is equall to no class
    :- p is eqall proportional of the class in dataset 
    :- if ginin is =0 the it will be perfectly pure node . as higher gingi than more impurity
example--> 
                if we have 10 sample 
                        four are red 
                        6 are green 
            proportional of red =4/10
            proportional of green=6/10
gini=1-(4)**2-(6)**2=0.48
(2)--->  what is information gain ?

it will measure the how much the information of uncentinaty is reduced after a dataset is split on an attribute 
it is based on entropy 
        formula ==> 

                    entropy= - sum(log(pi))
    example ---> 
                    let we have 10 sample 
                                4 sample are green
                                6 sampl are red 

we split it into two group ---> 
1) groups 1----> green----> 3green,1 red
2) groups 

total information gain:-ig = 0.971-(4/10*0.811+6/10*0.6540)
0.971-(0.324+0.340)
0.971 -0.714=0.257


4) mean squried error ==> when we use when we have target data in nemurical

In [5]:
import numpy as np 
import pandas as pd

In [7]:
df=pd.read_csv("C:\\Users\\Choud\\OneDrive\\Desktop\\data sets\\insurance - insurance.csv")

In [9]:
df.head(1)

   age     sex   bmi  children smoker     region    charges
0   19  female  27.9         0    yes  southwest  16884.924

In [11]:
df=pd.get_dummies(df, columns=['sex','smoker','region'])

In [13]:
df=df.astype(int)

In [15]:
x=df.drop(columns=['charges'])
y=df['charges']

In [17]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [21]:
from sklearn.tree import DecisionTreeRegressor

In [23]:
dt=DecisionTreeRegressor()

In [25]:
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [27]:
y_pred=dt.predict(x_test)

In [29]:
from sklearn.metrics import r2_score

In [31]:
r2_score(y_test,y_pred)

0.741397302799004

In [33]:
## when targe data "C:\Users\Choud\OneDrive\Desktop\data sets\Social_Network_Ads - Social_Network_Ads.csv"

## decision tree classifer

In [39]:
df=pd.read_csv("C:\\Users\\Choud\\OneDrive\\Desktop\\data sets\\Social_Network_Ads - Social_Network_Ads.csv")

In [41]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [43]:
df=pd.get_dummies(df, columns=['Gender'])

In [47]:
df=df.astype(int)

In [49]:
df.head(2)

    User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0  15624510   19            19000          0              0            1
1  15810944   35            20000          0              0            1

In [51]:
x=df.drop(columns=['Purchased'])
y=df['Purchased']

In [53]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [55]:
from sklearn.tree import DecisionTreeClassifier

In [57]:
dt=DecisionTreeClassifier()

In [59]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [61]:
y_pred=dt.predict(x_test)

In [63]:
from sklearn.metrics import accuracy_score

In [65]:
accuracy_score(y_test,y_pred)

0.8875

In [ ]:
## ctegricol