In [1]:
import numpy as np 
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\Choud\\OneDrive\\Desktop\\data sets\\covid_toy - covid_toy.csv")

In [3]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [4]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [9]:
df=df.dropna()

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
lb=LabelEncoder()

In [13]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid']=lb.fit_transform(df['has_covid'])

C:\Users\Choud\AppData\Local\Temp\ipykernel_328\2817386977.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = lb.fit_transform(df['gender'])
C:\Users\Choud\AppData\Local\Temp\ipykernel_328\2817386977.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cough'] = lb.fit_transform(df['cough'])
C:\Users\Choud\AppData\Local\Temp\ipykernel_328\2817386977.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'] = lb.fit_transform(df['city'])
C:\Users\Choud\AppData\Local\Temp\ipykernel_328\2817386977.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['has_covid']=lb.fit_transform(df['has_covid'])

In [17]:
df.head(2)

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1

In [19]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [21]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [27]:
knn= KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [29]:
y_pred=knn.predict(x_test)

In [51]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [53]:
accuracy_score(y_test,y_pred)

0.3888888888888889

In [55]:
confusion_matrix(y_test,y_pred)

array([[6, 2],
       [9, 1]], dtype=int64)

In [59]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.40      0.75      0.52         8\n           1       0.33      0.10      0.15        10\n\n    accuracy                           0.39        18\n   macro avg       0.37      0.42      0.34        18\nweighted avg       0.36      0.39      0.32        18\n'

In [35]:
df.shape

(90, 6)

## social network

In [142]:
df=pd.read_csv("C:\\Users\\Choud\\OneDrive\\Desktop\\data sets\\Social_Network_Ads - Social_Network_Ads.csv")

In [107]:
df.head(2)

    User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0
1  15810944   Male   35            20000          0

In [109]:
df.dropna()

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [111]:
from sklearn.preprocessing import LabelEncoder

In [113]:
lb=LabelEncoder()

In [115]:
df['Gender'] = lb.fit_transform(df['Gender'])

In [117]:
df.head(2)

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0

In [119]:
x=df.drop(columns=['Purchased'])
y=df['Purchased']

In [121]:
from sklearn.model_selection import train_test_split

In [123]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [125]:
from sklearn.neighbors import KNeighborsClassifier

In [129]:
knn= KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [131]:
y_pred=knn.predict(x_test)

In [133]:
from sklearn.metrics import accuracy_score

In [137]:
accuracy_score(y_test,y_pred)

0.7125

In [139]:
df.shape

(400, 5)